# Generated by Django 4.2.23 on 2025-06-24 07:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jawaban',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jawaban', models.CharField(max_length=1)),
                ('waktu_submit', models.DateTimeField(auto_now_add=True)),
                ('peserta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('soal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminpanel.soal')),
            ],
        ),
    ]
