# Generated by Django 4.2.23 on 2025-06-30 04:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0002_jawaban'),
    ]

    operations = [
        migrations.CreateModel(
            name='PesertaPaket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('waktu_mulai', models.DateTimeField(blank=True, null=True)),
                ('sudah_selesai', models.BooleanField(default=False)),
                ('paket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminpanel.paketsoal')),
                ('peserta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
