# Generated by Django 4.2.23 on 2025-07-01 08:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0003_pesertapaket'),
    ]

    operations = [
        migrations.CreateModel(
            name='PesertaSoalUrutan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('urutan', models.PositiveIntegerField()),
                ('paket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminpanel.paketsoal')),
                ('peserta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('soal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminpanel.soal')),
            ],
            options={
                'ordering': ['urutan'],
                'unique_together': {('peserta', 'urutan')},
            },
        ),
    ]
