# Generated by Django 4.2.23 on 2025-07-02 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0004_pesertasoalurutan'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='kelas',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
