# Generated by Django 4.2.23 on 2025-07-02 06:20

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0005_user_kelas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soal',
            name='teks',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
